[env:giga_r1_m7]
platform = ststm32
board = giga_r1_m7
framework = arduino

src_filter = +<*> -<ui/> -<Globals.cpp> -<Globals.h> -<sdram_init.h> -<sdram_init.cpp>

; Use the onboard debugger (CMSIS-DAP)
; debug_tool = cmsis-dap
; upload_protocol = mbed

; Libraries
lib_deps = 
    lvgl/lvgl
    arduino-libraries/Arduino_GigaDisplay@^1.0.2
    arduino-libraries/Arduino_GigaDisplay_GFX@^1.1.0
    arduino-libraries/Arduino_GigaDisplayTouch@^1.0.1
    arduino-libraries/NTPClient@^3.2.1
    QueueArray
    bblanchon/ArduinoJson@6.21.0

; build_flags =
    ; -v ; verbose
    ; -DUSBCON
    ; -DPIO_FRAMEWORK_ARDUINO_ENABLE_CDC
    ; -DUSBD_USE_CDC
    ; -O2
    ; -Os

; board_build.ldscript = ldscripts/giga_r1_m7_sdram.ld

[platformio]
extra_configs = ../common.ini