// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: bs_kettle_fill

#include "ui.h"

lv_obj_t *uic_ConfirmLabel2;
lv_obj_t *uic_SelectMode;
lv_obj_t *uic_BSLogo2;
lv_obj_t *ui_Screen2 = NULL;lv_obj_t *ui_Dropdown2 = NULL;lv_obj_t *ui_BSLogo2 = NULL;lv_obj_t *ui_SelectMode = NULL;lv_obj_t *ui_ConfirmUserButton1 = NULL;lv_obj_t *ui_UserDisplayLabel1 = NULL;lv_obj_t *ui_ConfirmLabel2 = NULL;
// event funtions
void ui_event_Dropdown2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      ( e );
      _ui_label_set_property(ui_UserDisplayLabel1, _UI_LABEL_PROPERTY_TEXT, "");
}
}

// build funtions

void ui_Screen2_screen_init(void)
{
ui_Screen2 = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Screen2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0xEE7B01), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Screen2, lv_color_hex(0x2E1A05), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_Screen2, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Dropdown2 = lv_dropdown_create(ui_Screen2);
lv_dropdown_set_options( ui_Dropdown2, "Kettle Fill\nWater Temp" );
lv_obj_set_width( ui_Dropdown2, 314);
lv_obj_set_height( ui_Dropdown2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Dropdown2, -164 );
lv_obj_set_y( ui_Dropdown2, 134 );
lv_obj_set_align( ui_Dropdown2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Dropdown2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_set_style_bg_color(ui_Dropdown2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Dropdown2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BSLogo2 = lv_image_create(ui_Screen2);
lv_image_set_src(ui_BSLogo2, &ui_img_buildshift_brand_png);
lv_obj_set_width( ui_BSLogo2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BSLogo2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BSLogo2, 11 );
lv_obj_set_y( ui_BSLogo2, -157 );
lv_obj_set_align( ui_BSLogo2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BSLogo2, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_BSLogo2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SelectMode = lv_label_create(ui_Screen2);
lv_obj_set_width( ui_SelectMode, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SelectMode, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SelectMode, -9 );
lv_obj_set_y( ui_SelectMode, -45 );
lv_obj_set_align( ui_SelectMode, LV_ALIGN_CENTER );
lv_label_set_text(ui_SelectMode,"Select Mode");
lv_obj_set_style_text_color(ui_SelectMode, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SelectMode, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SelectMode, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_SelectMode, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SelectMode, lv_color_hex(0x956207), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SelectMode, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_SelectMode, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_SelectMode, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ConfirmUserButton1 = lv_button_create(ui_Screen2);
lv_obj_set_width( ui_ConfirmUserButton1, 266);
lv_obj_set_height( ui_ConfirmUserButton1, 50);
lv_obj_set_x( ui_ConfirmUserButton1, 197 );
lv_obj_set_y( ui_ConfirmUserButton1, 134 );
lv_obj_set_align( ui_ConfirmUserButton1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ConfirmUserButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_ConfirmUserButton1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ConfirmUserButton1, lv_color_hex(0xF0A31E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ConfirmUserButton1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_ConfirmUserButton1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ConfirmUserButton1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_UserDisplayLabel1 = lv_label_create(ui_Screen2);
lv_obj_set_width( ui_UserDisplayLabel1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_UserDisplayLabel1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_UserDisplayLabel1, -12 );
lv_obj_set_y( ui_UserDisplayLabel1, 26 );
lv_obj_set_align( ui_UserDisplayLabel1, LV_ALIGN_CENTER );
lv_label_set_text(ui_UserDisplayLabel1,"Make a selection");
lv_obj_set_style_text_color(ui_UserDisplayLabel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_UserDisplayLabel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_UserDisplayLabel1, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ConfirmLabel2 = lv_label_create(ui_Screen2);
lv_obj_set_width( ui_ConfirmLabel2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ConfirmLabel2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ConfirmLabel2, 196 );
lv_obj_set_y( ui_ConfirmLabel2, 134 );
lv_obj_set_align( ui_ConfirmLabel2, LV_ALIGN_CENTER );
lv_label_set_text(ui_ConfirmLabel2,"confirm");
lv_obj_set_style_text_font(ui_ConfirmLabel2, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Dropdown2, ui_event_Dropdown2, LV_EVENT_ALL, NULL);
uic_BSLogo2 = ui_BSLogo2;
uic_SelectMode = ui_SelectMode;
uic_ConfirmLabel2 = ui_ConfirmLabel2;

}

void ui_Screen2_screen_destroy(void)
{
   if (ui_Screen2) lv_obj_del(ui_Screen2);

// NULL screen variables
ui_Screen2= NULL;
ui_Dropdown2= NULL;
uic_BSLogo2= NULL;
ui_BSLogo2= NULL;
uic_SelectMode= NULL;
ui_SelectMode= NULL;
ui_ConfirmUserButton1= NULL;
ui_UserDisplayLabel1= NULL;
uic_ConfirmLabel2= NULL;
ui_ConfirmLabel2= NULL;

}
