// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: bs_kettle_fill

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t *ui_Screen2;
extern void ui_event_Dropdown2( lv_event_t * e);
extern lv_obj_t *ui_Dropdown2;
extern lv_obj_t *ui_BSLogo2;
extern lv_obj_t *ui_SelectMode;
extern lv_obj_t *ui_ConfirmUserButton1;
extern lv_obj_t *ui_UserDisplayLabel1;
extern lv_obj_t *ui_ConfirmLabel2;
// CUSTOM VARIABLES
extern lv_obj_t *uic_BSLogo2;
extern lv_obj_t *uic_SelectMode;
extern lv_obj_t *uic_ConfirmLabel2;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

